In [12]:
import func3lt as f3  # transpose2d, window1d, convolution2d
import numpy as np
import sys

sys.path.append("..")

# Func 1

In [13]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(matrix)
transposed_matrix = f3.transpose2d(matrix)
print(transposed_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


# Func 2

In [18]:
# Define a 1D numpy array
input_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define the window size, shift, and stride
size = 3
shift = 2
stride = 1

# Call the window1d function
windows = f3.window1d(input_array, size, shift, stride)

# Print the resulting windows
for window in windows:
    print(window)

[1 2 3]
[3 4 5]
[5 6 7]
[7 8 9]


In [15]:
windows

[array([1, 2, 3]), array([3, 4, 5]), array([5, 6, 7]), array([7, 8, 9])]

# Func 3

In [20]:
input_matrix = np.array(
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])



kernel = np.array([[1, 0], [0, 1]])



print(f3.convolution2d(input_matrix, kernel, stride=2))

[[ 7. 11.]
 [23. 27.]]
